version: '3'

services:
  jupyter:
    build: ./notebook
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ${DATA_DIR}:/home/jovyan
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - VIRTUAL_HOST=${JUPYTER_HOST}
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=${JUPYTER_HOST}
    user: root

networks:
  default:
    external:
      name: ${NETWORK}
